#!/bin/bash

apt-get update  # To get the latest package lists
apt-get install libssl-dev
apt-get install virtualenv -y # To install Virtualenv
apt-get install python3-pip -y # To install python3

JUPYTER_DIR=/home/pi/astropi-notebook
mkdir -p -v "${JUPYTER_DIR}" # To create the Jupyter home directoryy
chown pi: "${JUPYTER_DIR}" # Change directory ownership to pi user

touch "${JUPYTER_DIR}"/run-jupyter-notebook.sh # Create jupyter startup script
cat <<EOF >"${JUPYTER_DIR}"/run-jupyter-notebook.sh # Content of jupyter startup script
#!/bin/bash
source /home/pi/jupyter-env/bin/activate
jupyter notebook --ip 0.0.0.0 --port 9999 --no-browser
deactivate
EOF

chmod +x "${JUPYTER_DIR}"/run-jupyter-notebook.sh # Make jupyter startup script executable
chown pi: "${JUPYTER_DIR}"/run-jupyter-notebook.sh # Change ownership of jupyter startup script to pi user

VENV=/home/pi/jupyter-env
virtualenv -q -p python3 $VENV  # To create a python3 Virtualenv
#source $VENV//bin/activate 
#$VENV/bin/pip install numpy
#$VENV/bin/pip install pytest
#$VENV/bin/pip install scipy
#$VENV/bin/pip install h5py
#$VENV/bin/pip install beautifulsoup4
#$VENV/bin/pip install html5lib
#$VENV/bin/pip install bleach
#$VENV/bin/pip install pyyaml
#$VENV/bin/pip install pandas
#$VENV/bin/pip install bintrees
#$VENV/bin/pip install sortedcontainers
#$VENV/bin/pip install jplephem
#$VENV/bin/pip install matplotlib
#$VENV/bin/pip install scikit-image
#$VENV/bin/pip install setuptools
#$VENV/bin/pip install mpmath
#$VENV/bin/pip install asdf
#$VENV/bin/pip install bottleneck
#$VENV/bin/pip install astropy
#source $VENV/bin/deactivate

