#!/bin/bash

apt-get update  # To get the latest package lists
apt-get install libssl-dev
apt-get install virtualenv -y # To install Virtualenv
apt-get install python3-pip -y # To install python3

JUPYTER_DIR=/home/pi/astropi-notebook
mkdir -p -v "${JUPYTER_DIR}" # To create the Jupyter home directoryy
chown pi: "${JUPYTER_DIR}" # Change directory ownership to pi user

touch "${JUPYTER_DIR}"/run-jupyter-notebook.sh # Create jupyter startup script
cat <<EOF >"${JUPYTER_DIR}"/run-jupyter-notebook.sh # Content of jupyter startup script
#!/bin/bash
source /home/pi/jupyter-env/bin/activate
jupyter notebook --ip 0.0.0.0 --port 9999 --no-browser
deactivate
EOF

chmod +x "${JUPYTER_DIR}"/run-jupyter-notebook.sh # Make jupyter startup script executable
chown pi: "${JUPYTER_DIR}"/run-jupyter-notebook.sh # Change ownership of jupyter startup script to pi user

VENV=/home/pi/jupyter-env
virtualenv -q -p python3 $VENV  # To create a python3 Virtualenv
$VENV//bin/activate 
$VENV/bin/pip install -y numpy
$VENV/bin/pip install -y pytest
$VENV/bin/pip install -y scipy
$VENV/bin/pip install -y h5py
$VENV/bin/pip install -y beautifulsoup4
$VENV/bin/pip install -y html5lib
$VENV/bin/pip install -y bleach
$VENV/bin/pip install -y pyyaml
$VENV/bin/pip install -y pandas
$VENV/bin/pip install -y bintrees
$VENV/bin/pip install -y sortedcontainers
$VENV/bin/pip install -y jplephem
$VENV/bin/pip install -y matplotlib
$VENV/bin/pip install -y scikit-image
$VENV/bin/pip install -y setuptools
$VENV/bin/pip install -y mpmath
$VENV/bin/pip install -y asdf
$VENV/bin/pip install -y bottleneck
$VENV/bin/pip install -y astropy
$VENV/bin/deactivate

